runtime: nodejs18

env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always

# Skip files that shouldn't be uploaded
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?node_modules/.*$
- ^(.*/)?tests/.*$
- ^(.*/)?test/.*$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.log$
- ^(.*/)?.*\.env$
- ^(.*/)?.*\.env\..*$
- ^(.*/)?Dockerfile$
- ^(.*/)?docker-compose\.yml$
- ^(.*/)?.*\.git.*$